try:
    # code that may rais an execption
    risky_code()
except Exception as e:
    print(f'Error occurred: {e}')